# configuration for the acts_as_ferret DRb server
# host: where to reach the DRb server (used by application processes to contact the server)
# port: which port the server should listen on
# socket: where the DRb server should create the socket (absolute path), this setting overrides host:port configuration
# pid_file: location of the server's pid file (relative to RAILS_ROOT)
# log_file: log file (default: RAILS_ROOT/log/ferret_server.log
# log_level: log level for the server's logger
production:
  enable_star: 1
  #address: localhost
  port: 9001
  #bin_path: /usr/bin
  searchd_binary_name: /usr/bin/searchd
  indexer_binary_name: /usr/bin/indexer
# aaf won't try to use the DRb server in environments that are not 
# configured here.
development:
  enable_star: 1
  address: localhost
  min_infix_len: 2
  port: 1234
  chunk_size: 80
  limit: 80
  bin_path: /usr/bin
#test:
#  host: localhost
#  port: 9009
#  pid_file: log/ferret.pid
